### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by lxbarbosa** [lxbarbosa/novels.org#6]
Alphapapa project, a great choice: https://github.com/alphapapa/org-make-toc

**Comment by lxbarbosa** [comment]
done in https://github.com/lxbarbosa/novels.org/commit/03a52e3eb876c62b692a19f74989309689fc0b08

**Comment by lxbarbosa** [comment]
Add missing TOC in some files and ignore this attribute

**Comment by alphapapa** [comment]
Cool!  Thanks for letting me know.
